Repository himanshu007-creator/SFC-foundations, pull requests merged in 2021-05, with the labels that each got.

#231 Contactus Page
  css/Contact-Us/contactus.css
  images/contactbg (2).gif
  index.html
  js/Contact-Us/contactus.js
  pages/Contact-Us/contact.html
Labels: Level3, gssoc21

#237 Included Python and Django badges in tech stack (README) #235
  README.md
Labels: Level0, gssoc21

#241 Blog Page
  css/Blog/blog.css
  index.html
  js/Blog/blog.js
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
Labels: Level3, gssoc21

#244 Template
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  index.html
  js/Templates/blog.js
  js/Templates/event.js
  js/Templates/news.js
  pages/Blog/blog.html
  pages/Events/events.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
Labels: Level3, gssoc21

#187 Map integration Done
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/style.css
  index.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
  present_source_code/index.html
Labels: Level3, gssoc21

#253 Kmp Page
  css/KMP/kmp.css
  css/style.css
  index.html
  js/KMP/kmp.js
  js/News/news.js
  pages/KMP/kmp.html
  pages/News/news.html
Labels: Level3, gssoc21

#232 Donate page
  .DS_Store
  Assets/Donate.html
  Assets/index.html
  Assets/style.css
  css/darkmode.css
  css/style.css
  images/.DS_Store
  images/bg.jpg
  images/crowd funding.jpg
  images/donatenowbg.jpg
  images/scholoarship.jpg
  images/shape a future.jpg
  images/volunter-bg.jpg
  index.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
Labels: Level3, gssoc21

#259 Backend Updated: Blog added(almost completed)
  app/__pycache__/__init__.cpython-39.pyc
  app/__pycache__/admin.cpython-39.pyc
  app/__pycache__/apps.cpython-39.pyc
  app/__pycache__/forms.cpython-39.pyc
  app/__pycache__/models.cpython-39.pyc
  app/__pycache__/urls.cpython-39.pyc
  app/__pycache__/views.cpython-39.pyc
  app/admin.py
  app/forms.py
  app/migrations/0002_auto_20210509_1537.py
  app/migrations/0003_alter_blogpost_date.py
  app/migrations/0004_blogpost_image.py
  app/migrations/0005_remove_blogpost_image.py
  app/migrations/0006_blogpost_image.py
  app/migrations/0007_blogpostcomment.py
  app/migrations/0008_remove_blogpost_image.py
  app/migrations/0009_auto_20210510_1720.py
  app/migrations/0010_blogpost_role.py
  app/migrations/0011_blogpost_image.py
  app/migrations/0012_alter_blogpost_image.py
  app/migrations/__pycache__/0001_initial.cpython-39.pyc
  app/migrations/__pycache__/0002_auto_20210509_1537.cpython-39.pyc
  app/migrations/__pycache__/0003_alter_blogpost_date.cpython-39.pyc
  app/migrations/__pycache__/0004_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0005_remove_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0006_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0007_blogpostcomment.cpython-39.pyc
  app/migrations/__pycache__/0008_remove_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0009_auto_20210510_1720.cpython-39.pyc
  app/migrations/__pycache__/0010_blogpost_role.cpython-39.pyc
  app/migrations/__pycache__/0011_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0012_alter_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/__init__.cpython-39.pyc
  app/models.py
  app/static/css/Blog/blog.css
  app/static/css/style.css
  app/template/pages/Blog/blog.html
  app/template/pages/Blog/blog_detail.html
  app/template/pages/Blog/blog_list.html
  app/template/pages/Blog/blogtest.html
  app/template/pages/Blog/comment_form.html
  app/template/pages/Blog/post_confirm_delete.html
  app/template/pages/Blog/post_detail.html
  app/template/pages/Blog/post_list.html
  app/urls.py
  app/views.py
  backend/__pycache__/__init__.cpython-39.pyc
  backend/__pycache__/settings.cpython-39.pyc
  backend/__pycache__/urls.cpython-39.pyc
  backend/__pycache__/wsgi.cpython-39.pyc
  backend/settings.py
  backend/urls.py
  db.sqlite3
  media/blogMedia/cover.png
  requirements.txt
Labels: Level3, gssoc21

#261 Added: blog comments
  app/__pycache__/__init__.cpython-39.pyc
  app/__pycache__/admin.cpython-39.pyc
  app/__pycache__/apps.cpython-39.pyc
  app/__pycache__/forms.cpython-39.pyc
  app/__pycache__/models.cpython-39.pyc
  app/__pycache__/urls.cpython-39.pyc
  app/__pycache__/views.cpython-39.pyc
  app/forms.py
  app/migrations/0013_auto_20210511_1429.py
  app/migrations/0014_blogpostcomment_approved.py
  app/migrations/__pycache__/0001_initial.cpython-39.pyc
  app/migrations/__pycache__/0002_auto_20210509_1537.cpython-39.pyc
  app/migrations/__pycache__/0003_alter_blogpost_date.cpython-39.pyc
  app/migrations/__pycache__/0004_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0005_remove_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0006_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0007_blogpostcomment.cpython-39.pyc
  app/migrations/__pycache__/0008_remove_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0009_auto_20210510_1720.cpython-39.pyc
  app/migrations/__pycache__/0010_blogpost_role.cpython-39.pyc
  app/migrations/__pycache__/0011_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0012_alter_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0013_auto_20210511_1429.cpython-39.pyc
  app/migrations/__pycache__/0014_blogpostcomment_approved.cpython-39.pyc
  app/migrations/__pycache__/__init__.cpython-39.pyc
  app/models.py
  app/template/pages/Blog/blog_detail.html
  app/views.py
  backend/__pycache__/__init__.cpython-39.pyc
  backend/__pycache__/settings.cpython-39.pyc
  backend/__pycache__/urls.cpython-39.pyc
  backend/__pycache__/wsgi.cpython-39.pyc
  backend/urls.py
  db.sqlite3
Labels: Level1, gssoc21

#263 Added Comment Feature in Backend
  app/models.py
  app/template/pages/Blog/blog_detail.html
  app/urls.py
  app/views.py
Labels: Level3, gssoc21

#257 News Page added !
  css/News/news.css
  pages/News/news.html
Labels: Level3, gssoc21

#264 completed blog section
  app/__pycache__/models.cpython-39.pyc
  app/__pycache__/urls.cpython-39.pyc
  app/__pycache__/views.cpython-39.pyc
  app/models.py
  app/template/pages/Blog/blog_detail.html
  db.sqlite3
Labels: Level3, gssoc21

#266 added editor to news_admin
  app/__pycache__/__init__.cpython-38.pyc
  app/__pycache__/admin.cpython-38.pyc
  app/__pycache__/apps.cpython-38.pyc
  app/__pycache__/models.cpython-38.pyc
  app/__pycache__/urlsBlog.cpython-38.pyc
  app/__pycache__/urlsNews.cpython-38.pyc
  app/__pycache__/views.cpython-38.pyc
  app/admin.py
  app/migrations/__pycache__/0001_initial.cpython-38.pyc
  app/migrations/__pycache__/0002_auto_20210509_1537.cpython-38.pyc
  app/migrations/__pycache__/0003_alter_blogpost_date.cpython-38.pyc
  app/migrations/__pycache__/0004_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0005_remove_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0006_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0007_blogpostcomment.cpython-38.pyc
  app/migrations/__pycache__/0008_remove_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0009_auto_20210510_1720.cpython-38.pyc
  app/migrations/__pycache__/0010_blogpost_role.cpython-38.pyc
  app/migrations/__pycache__/0011_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0012_alter_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0013_auto_20210511_1429.cpython-38.pyc
  app/migrations/__pycache__/0014_blogpostcomment_approved.cpython-38.pyc
  app/migrations/__pycache__/0015_news.cpython-38.pyc
  app/migrations/__pycache__/0016_rename_news_new.cpython-38.pyc
  app/migrations/__pycache__/0017_alter_new_subtitle.cpython-38.pyc
  app/migrations/__pycache__/0018_auto_20210512_1822.cpython-38.pyc
  app/migrations/__pycache__/0019_new_source.cpython-38.pyc
  app/migrations/__pycache__/0020_alter_new_source.cpython-38.pyc
  app/migrations/__pycache__/__init__.cpython-38.pyc
  app/static/js/adminjs/admin_blog.js
  app/static/js/adminjs/admin_news.js
  app/template/pages/news/newsDetail.html
  backend/__pycache__/__init__.cpython-38.pyc
  backend/__pycache__/settings.cpython-38.pyc
  backend/__pycache__/urls.cpython-38.pyc
  backend/__pycache__/wsgi.cpython-38.pyc
  db.sqlite3
  media/newsMedia/3c020b67eecda2f4d9a3ade4d6a3e98a11a4af00ecc9537e0307b2bb.ico
Labels: Level3, gssoc21

#267 added event (dynamic content injecting)
  app/__pycache__/admin.cpython-39.pyc
  app/__pycache__/models.cpython-39.pyc
  app/__pycache__/urlsBlog.cpython-39.pyc
  app/__pycache__/urlsEvent.cpython-39.pyc
  app/__pycache__/urlsNews.cpython-39.pyc
  app/__pycache__/views.cpython-39.pyc
  app/admin.py
  app/migrations/0021_event.py
  app/migrations/__pycache__/0021_event.cpython-39.pyc
  app/models.py
  app/static/css/Events/events.css
  app/static/css/Templates/event.css
  app/template/pages/Events/eventDetail.html
  app/template/pages/Events/eventList.html
  app/template/pages/Join-Us/joinus.html
  app/urlsBlog.py
  app/urlsEvent.py
  app/urlsNews.py
  app/views.py
  backend/__pycache__/urls.cpython-39.pyc
  backend/urls.py
  db.sqlite3
  media/eventMedia/Koala.jpg
  media/eventMedia/Koala_2SZAgRD.jpg
  media/eventMedia/Koala_KCvcScg.jpg
  media/eventMedia/Koala_vswALzO.jpg
  media/eventMedia/Koala_wgY0BGs.jpg
Labels: Level3, gssoc21

#269 texteditor to event admin page
  app/__pycache__/__init__.cpython-38.pyc
  app/__pycache__/admin.cpython-38.pyc
  app/__pycache__/apps.cpython-38.pyc
  app/__pycache__/models.cpython-38.pyc
  app/__pycache__/urlsBlog.cpython-38.pyc
  app/__pycache__/urlsEvent.cpython-38.pyc
  app/__pycache__/urlsNews.cpython-38.pyc
  app/__pycache__/views.cpython-38.pyc
  app/admin.py
  app/migrations/__pycache__/0001_initial.cpython-38.pyc
  app/migrations/__pycache__/0002_auto_20210509_1537.cpython-38.pyc
  app/migrations/__pycache__/0003_alter_blogpost_date.cpython-38.pyc
  app/migrations/__pycache__/0004_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0005_remove_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0006_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0007_blogpostcomment.cpython-38.pyc
  app/migrations/__pycache__/0008_remove_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0009_auto_20210510_1720.cpython-38.pyc
  app/migrations/__pycache__/0010_blogpost_role.cpython-38.pyc
  app/migrations/__pycache__/0011_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0012_alter_blogpost_image.cpython-38.pyc
  app/migrations/__pycache__/0013_auto_20210511_1429.cpython-38.pyc
  app/migrations/__pycache__/0014_blogpostcomment_approved.cpython-38.pyc
  app/migrations/__pycache__/0015_news.cpython-38.pyc
  app/migrations/__pycache__/0016_rename_news_new.cpython-38.pyc
  app/migrations/__pycache__/0017_alter_new_subtitle.cpython-38.pyc
  app/migrations/__pycache__/0018_auto_20210512_1822.cpython-38.pyc
  app/migrations/__pycache__/0019_new_source.cpython-38.pyc
  app/migrations/__pycache__/0020_alter_new_source.cpython-38.pyc
  app/migrations/__pycache__/0021_event.cpython-38.pyc
  app/migrations/__pycache__/__init__.cpython-38.pyc
  app/static/js/adminjs/admin_news.js
  app/static/js/adminjs/admin_pg.js
  app/template/pages/Events/eventDetail.html
  backend/__pycache__/__init__.cpython-38.pyc
  backend/__pycache__/settings.cpython-38.pyc
  backend/__pycache__/urls.cpython-38.pyc
  backend/__pycache__/wsgi.cpython-38.pyc
  db.sqlite3
Labels: Level3, gssoc21

#270 Feed Logo
  css/style.css
  images/ANimal Rescue.gif
  index.html
Labels: Level2, gssoc21

#272 Added links to README.md
  README.md
Labels: First timers only, Level0, gssoc21

#275 Made Site Responsive !!
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/style.css
  index.html
  pages/About-Us/coreteam.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/KMP/kmp.html
  pages/News/news.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
Labels: Level2, gssoc21

#276 Made event image optional
  app/__pycache__/__init__.cpython-39.pyc
  app/__pycache__/admin.cpython-39.pyc
  app/__pycache__/apps.cpython-39.pyc
  app/__pycache__/models.cpython-39.pyc
  app/__pycache__/urlsBlog.cpython-39.pyc
  app/__pycache__/urlsEvent.cpython-39.pyc
  app/__pycache__/urlsNews.cpython-39.pyc
  app/__pycache__/views.cpython-39.pyc
  app/migrations/0022_auto_20210517_2035.py
  app/migrations/__pycache__/0001_initial.cpython-39.pyc
  app/migrations/__pycache__/0002_auto_20210509_1537.cpython-39.pyc
  app/migrations/__pycache__/0003_alter_blogpost_date.cpython-39.pyc
  app/migrations/__pycache__/0004_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0005_remove_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0006_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0007_blogpostcomment.cpython-39.pyc
  app/migrations/__pycache__/0008_remove_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0009_auto_20210510_1720.cpython-39.pyc
  app/migrations/__pycache__/0010_blogpost_role.cpython-39.pyc
  app/migrations/__pycache__/0011_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0012_alter_blogpost_image.cpython-39.pyc
  app/migrations/__pycache__/0013_auto_20210511_1429.cpython-39.pyc
  app/migrations/__pycache__/0014_blogpostcomment_approved.cpython-39.pyc
  app/migrations/__pycache__/0015_news.cpython-39.pyc
  app/migrations/__pycache__/0016_rename_news_new.cpython-39.pyc
  app/migrations/__pycache__/0017_alter_new_subtitle.cpython-39.pyc
  app/migrations/__pycache__/0018_auto_20210512_1822.cpython-39.pyc
  app/migrations/__pycache__/0019_new_source.cpython-39.pyc
  app/migrations/__pycache__/0020_alter_new_source.cpython-39.pyc
  app/migrations/__pycache__/0021_event.cpython-39.pyc
  app/migrations/__pycache__/0022_auto_20210517_2035.cpython-39.pyc
  app/migrations/__pycache__/__init__.cpython-39.pyc
  app/models.py
  app/template/pages/Events/eventDetail.html
  backend/__pycache__/__init__.cpython-39.pyc
  backend/__pycache__/settings.cpython-39.pyc
  backend/__pycache__/urls.cpython-39.pyc
  backend/__pycache__/wsgi.cpython-39.pyc
  db.sqlite3
  media/eventMedia/Koala_VYih5MQ.jpg
  media/eventMedia/Koala_z4nthHw.jpg
  media/eventMedia/morgan-codes-wallpaper_qhJis1A.png
  media/eventMedia/pexels-drmakete-lab-48828_qFVRkpa.jpg
  requirements.txt
Labels: Level3, gssoc21

#279 Coreteam & kmp
  css/About-Us/coreteam.css
  css/KMP/kmp.css
  pages/KMP/kmp.html
Labels: Level3, gssoc21

#281 Fixed navbar links
  pages/About-Us/coreteam.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Donate/Donate.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/KMP/kmp.html
  pages/News/news.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
Labels: Level1, gssoc21

#284 Updated Contributing .md file
  CONTRIBUTING.md
Labels: Level1, gssoc21

#287 Readmodi
  Assets/CodingGIF.gif
  README.md
Labels: Level1, gssoc21

#296 Contact us footer changes
  css/Contact-Us/contactus.css
  pages/Contact-Us/contact.html
Labels: Level1, gssoc21

#297 Porject page margin bug
  css/Join-Us/joinus.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
Labels: Level2, gssoc21

#298 Removed Explore Button & Added Wave feature
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/style.css
  index.html
  pages/About-Us/coreteam.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/KMP/kmp.html
  pages/News/news.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
Labels: Level3, gssoc21

#300 Reordered Project in Index page !!
  index.html
Labels: Level2, gssoc21

#304 Removed img from JOin us page of intern section
  pages/Join-Us/joinus.html
Labels: Level1, gssoc21

#302 Made the pre loader round in shape
  css/style.css
Labels: Level1, gssoc21

#307 Contact us Button !!
  css/Contact-Us/contactus.css
  pages/Contact-Us/contact.html
Labels: Level1, gssoc21

#312 event page to slider template updated
  css/slider-event/slider-event.css
  pages/slider-event/slider-event.html
Labels: Level3, gssoc21

#310 Fixed the issue of navbar in DarkMode
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/style.css
Labels: Level2, gssoc21

#318 Modified Feed Us Section
  Assets/style.css
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/slider-event/slider-event.css
  css/style.css
Labels: Level2, gssoc21

#316 Dark Mode Bug fixed in news button
  css/style.css
  index.html
Labels: Level3, gssoc21

#323 added btn
  css/style.css
  index.html
Labels: Level2, gssoc21

#322 Changed hamburger menu Icon
  Assets/index.html
  index.html
  pages/About-Us/coreteam.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/KMP/kmp.html
  pages/News/news.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
  pages/slider-event/slider-event.html
Labels: Level1, gssoc21

#324 Made changes in KMP pages !
  css/KMP/kmp.css
Labels: Level2, gssoc21

#327 Changed path to load image of Gyan project instead of Sampuran project
  Assets/index.html
Labels: Level1, gssoc21

#337 updated content in team delhi
  images/Aditi Singh_Project Sampuran.jpeg
  images/Anshaj Srivastava_General Secy.jpeg
  images/Ayush Krishna_ Technical and Editorial Head.jpg
  images/Ishana Dhingra_ Project Gyan Head.jpeg
  images/Shivangi Srivastava_ Project Vatavaran.jpg
  images/Tabassum Naaz_President.jpeg
  images/aastha khera; president.jpg
  images/gurleen;General secretary.jpeg
  images/himanshu; gyan head.jpeg
  images/kartavya bhayana; vatavaran head.jpg
  images/swapnil dadwal; sampuran head.jpeg
  pages/About-Us/coreteam.html
Labels: Level2, gssoc21

#335 updated team c content
  images/ANKITA MARYA, SENIOR EDITOR.jpeg
  images/DISHA GOYAL, PRESIDENT.jpeg
  images/MANISH SHARMA,SAMPURAN HEAD.jpg
  images/NEHA SOOD, GENERAL SECRETARY.jpeg
  images/PRIYANKA SHARMA ,GYAN HEAD.jpg
  pages/About-Us/coreteam.html
Labels: Level2, gssoc21

#333 Made changes in core team main page paragraph
  pages/About-Us/coreteam.html
Labels: Level1, gssoc21

#340 updated content of mumbai branch
  images/Ayush Gada, VATAVARAN HEAD.jpeg
  images/KOMAL SHAH, GYAN HEAD.jpeg
  images/PALAK SHAH ,PRESIDENT.jpeg
  images/RAAJALAKSHMI IYER, GENERAL SECRETARY.jpg
  images/VINITA, SAMPURAN HEAD.jpg
  pages/About-Us/coreteam.html
Labels: Level2, gssoc21

#349 updated the content of working model
  pages/About-Us/workingmodel.html
Labels: Level2, gssoc21

#347 updated the content of objective page
  pages/About-Us/objectives.html
Labels: Level2, gssoc21

#345 updated the content of know sfc page
  pages/About-Us/knowsfc.html
Labels: Level2, gssoc21

#343 updated the bio of founder
  pages/About-Us/founder.html
Labels: Level1, gssoc21

#351 updated the content of join us page
  pages/Join-Us/joinus.html
Labels: Level2, gssoc21

#358 Contact us turns yellow when opened
  pages/Contact-Us/contact.html
Labels: Level1, gssoc21

#359 Changed HamburgerMenu Background
  Assets/style.css
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/slider-event/slider-event.css
  css/style.css
Labels: Level2, gssoc21

#364 removed feed from all pages except index
  pages/About-Us/coreteam.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Events/events.html
  pages/Join-Us/joinus.html
  pages/KMP/kmp.html
  pages/News/news.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
  pages/Templates/blog.html
  pages/Templates/event.html
  pages/Templates/news.html
  pages/slider-event/slider-event.html
Labels: Level2, gssoc21

#361 Hover on btn darkmode
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/slider-event/slider-event.css
  css/style.css
Labels: Level2, gssoc21

#366 Modified code of conduct
  CODE_OF_CONDUCT.md
Labels: Level1, gssoc21

#365 added the top section of know sfc page
  css/About-Us/knowsfc.css
  images/trial1.jpeg
  images/trial2.jpeg
  images/trial3.jpeg
  pages/About-Us/knowsfc.html
Labels: Level3, gssoc21

#369 Modified HamburgerMenuHover
  Assets/style.css
  css/About-Us/coreteam.css
  css/About-Us/founder.css
  css/About-Us/knowsfc.css
  css/About-Us/objectives.css
  css/About-Us/workingmodel.css
  css/Blog/blog.css
  css/Contact-Us/contactus.css
  css/Events/events.css
  css/Join-Us/joinus.css
  css/KMP/kmp.css
  css/News/news.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/Templates/blog.css
  css/Templates/event.css
  css/Templates/news.css
  css/slider-event/slider-event.css
  css/style.css
Labels: Level2, gssoc21

#370 Images changed
  images/banner.png
  images/joinusbanner.png
  index.html
Labels: Level2, gssoc21

#325 Update coreteam.css
  css/About-Us/coreteam.css
Labels: Level1, gssoc21

#388 added hexagon design for web version only
  css/About-Us/knowsfc.css
  pages/About-Us/knowsfc.html
Labels: Level2, gssoc21

#389 Fixed the issue of 3rd person going out of the screen
  css/About-Us/coreteam.css
Labels: Level1, gssoc21

#390 fixed btn of core team selction
  css/About-Us/coreteam.css
Labels: Level2, gssoc21

#397 aligned for all three devices
  css/style.css
Labels: Level2, gssoc21

#395 darkmode in tablet
  Assets/style.css
Labels: Level1, gssoc21

#394 made the manual btn of sider alling know sfc page
  css/About-Us/knowsfc.css
Labels: Level2, gssoc21

#393 fixed the nav btn on home page slider
  css/style.css
Labels: Level1, gssoc21

#392 made tablet version of kmp page
  css/KMP/kmp.css
Labels: Level2, gssoc21
