Repository himanshu007-creator/SFC-foundations, pull requests merged in 2021-04, with the labels that each got.

#138 Fix the relevance attribute #137
  index.html
Labels: Level0, gssoc21

#141 map added
  index.html
Labels: Level2, gssoc21

#152 Added Issue template
  .github/ISSUE_TEMPLATE/custom.md
Labels: Level0, gssoc21

#153 darkmode
  css/style.css
  images/Darkmode.jpg
  images/Lightmode.jpg
  index.html
  js/script.js
Labels: Level1, gssoc21

#165 [Gssoc21] Added the smooth scrolling
  css/style.css
Labels: Level0, gssoc21

#166 [Gssoc'21] Fixed the Responsiveness of Preloader
  css/style.css
Labels: Level1, gssoc21

#167 Updated Readme
  README.md
Labels: Level0, gssoc21

#177 Added Favicon
  css/style.css
  images/Darkmode.jpg
  images/Lightmode.jpg
  index.html
  js/script.js
Labels: Level1, gssoc21

#115 Contact us form design
  Assets/Contact_us/contact us design.jpeg
Labels: Level1, gssoc21

#186 Added no.of forks,stars,issues,pr's and liscense,reposize in readme file
  README.md
Labels: Level0, gssoc21

#189 Gyan Page added
  css/gyan.css
  index.html
  js/gyan.js
  pages/gyan.html
Labels: Level2, gssoc21

#191 Add Page Vatavaran
  css/vatavaran.css
  index.html
  js/vatavaran.js
  pages/vatavaran.html
Labels: Level3, gssoc21

#194 new Darkmode Toggler and fix the but in it
  css/darkmode.css
  css/style.css
  index.html
  js/darkmode.js
Labels: Level1, gssoc21

#196 Darkmode to Pages
  css/Sampuran.css
  css/gyan.css
  css/vatavaran.css
  pages/Sampuran.html
  pages/gyan.html
  pages/vatavaran.html
Labels: Level1, gssoc21

#198 Added Page Join-Us Intern
  css/Join-Us/joinus.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/style.css
  images/INTERN.jpg
  index.html
  js/Join-Us/joinus.js
  js/Projects/Sampuran.js
  js/Projects/gyan.js
  js/Projects/vatavaran.js
  pages/Join-Us/joinus.html
  pages/Projects/Sampuran.html
  pages/Projects/gyan.html
  pages/Projects/vatavaran.html
Labels: Level3, gssoc21

#203 About us Section Redesigned
  css/style.css
  index.html
Labels: Level3, gssoc21

#205 Created Page Know sfc
  css/About-Us/knowsfc.css
  images/knowsfc.jpeg
  index.html
  js/About-Us/knowsfc.js
  pages/About-Us/knowsfc.html
Labels: Level3, gssoc21

#209 Nav bar Fixed
  css/About-Us/knowsfc.css
  css/Join-Us/joinus.css
  css/Projects/Sampuran.css
  css/Projects/gyan.css
  css/Projects/vatavaran.css
  css/style.css
  images/banner.png
  images/joinusbanner.png
  index.html
  pages/Join-Us/joinus.html
Labels: Level2, gssoc21

#211 Added Page Working model
  css/About-Us/workingmodel.css
  index.html
  js/About-Us/workingmodel.js
  pages/About-Us/workingmodel.html
Labels: Level3, gssoc21

#214 Upcoming events section redesigned
  css/style.css
  index.html
Labels: Level3, gssoc21

#220 Added the wave to home page
  css/style.css
  index.html
Labels: Level3, gssoc21

#219 Founderprofile Page added
  css/About-Us/founder.css
  images/founder.png
  index.html
  js/About-Us/founder.js
  pages/About-Us/founder.html
Labels: Level3, gssoc21
