Repository himanshu007-creator/SFC-foundations, pull requests merged in 2021-03, with the labels that each got.

#19 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level0, gssoc21

#87 Label commenter bot
  .github/label-commenter-config.yml
  .github/workflows/label-commenter.yml
Labels: Level2, gssoc21

#89 Update README.md
  README.md
Labels: Level0, gssoc21

#93 Label commenter bot bug
  .github/label-commenter-config.yml
  .github/workflows/label-commenter.yml
Labels: gssoc21

#95 Added Contributors
  README.md
Labels: Level0, gssoc21

#96 Added Tech stacks used
  README.md
Labels: Level0, gssoc21

#100 Update README.md and added Some GIFs
  README.md
Labels: Level0, gssoc21

#105 Adding a CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: Level0, gssoc21

#110 Update README.md
  README.md
Labels: Level0, gssoc21

#111 Design for the Homepage Attached
  Design/Homepage/1.jpg
  Design/Homepage/2.jpg
  Design/Homepage/3.jpg
  Design/Homepage/4.jpg
  Design/Homepage/5.jpg
  Design/Homepage/6.jpg
Labels: Level2, gssoc21
