Repository himanshu007-creator/SFC-foundations, pull requests merged in 2021-07, with the labels that each got.

#422 [MASTER] Added tribute to contributors.
  README.md
  Tribute_To_Contributors.html
Labels: LGMSOC21, 🟩Level1

#425 Changes made on Feed Page
  css/FEED/feed.css
Labels: LGMSOC21, 🟩Level1

#430 Changes done
  index.html
  pages/FEED/feed.html
Labels: LGMSOC21, 🟦Level0

#432 added coreteam button link
  css/About-Us/knowsfc.css
  pages/About-Us/knowsfc.html
Labels: LGMSOC21, 🟧Level3

#434 Hexagon alignment fixes
  css/About-Us/knowsfc.css
  pages/About-Us/hexagon.png
  pages/About-Us/knowsfc.html
Labels: LGMSOC21, 🟥Level4

#426 Home page live button bug fixed
  css/style.css
  index.html
Labels: LGMSOC21, 🟨Level2

#436 Layout
  CodeArchitecture.md
  README.md
  Tribute_To_Contributors.html
  css/About-Us/knowsfc.css
  css/FEED/feed.css
  css/style.css
  images/ANKITA.KMP.png
  images/DISHA.KMP.png
  images/FOUNDERIMG.png
  images/HIMANSHU.KMP.png
  images/hexagon.png
  index.html
  pages/About-Us/coreteam.html
  pages/About-Us/founder.html
  pages/About-Us/knowsfc.html
  pages/About-Us/objectives.html
  pages/About-Us/workingmodel.html
  pages/Blog/blog.html
  pages/Contact-Us/contact.html
  pages/Donate/Donate.html
  pages/Events/events.html
  pages/FEED/feed.html
  pages/Join-Us/joinus.html
  pages/KMP/kmp.html
Labels: LGMSOC21, 🟨Level2
